CREATE PROCEDURE sp_CadastraAluno
(
    @NOME VARCHAR(50),
    @CURSO CHAR(3),
    @PERLETIVO int
)
AS
BEGIN
	DECLARE @MATRICULA int
	
	INSERT INTO ALUNOS (NOME) VALUES (@NOME)

	SET @MATRICULA = (SELECT IDENT_CURRENT('ALUNOS') AS [IDENT_CURRENT])
	
	INSERT INTO MATRICULA (MATRICULA, CURSO, MATERIA, PROFESSOR, PERLETIVO)
	SELECT ALUNOS.MATRICULA , MATERIAS.CURSO, MATERIAS.SIGLA , MATERIAS.PROFESSOR, @PERLETIVO as PERLETIVO
	FROM MATERIAS, ALUNOS
	WHERE ALUNOS.MATRICULA = @MATRICULA and MATERIAS.CURSO = @CURSO
	
	SELECT * FROM MATRICULA INNER JOIN ALUNOS ON ALUNOS.MATRICULA = MATRICULA.MATRICULA WHERE ALUNOS.MATRICULA = @MATRICULA

END;

EXEC sp_CadastraAluno  @NOME= 'Dornel Topi', @CURSO = 'ENG',  @PERLETIVO = 2020

