CREATE PROCEDURE sp_CadastraAluno
(
    @NOME VARCHAR(50),
    @CURSO CHAR(3),
    @MATERIA CHAR(3),
    @PROFESSOR int,
    @PERLETIVO int
)
AS
BEGIN
	DECLARE @MATRICULA int
	
	INSERT INTO ALUNOS (NOME) VALUES (@NOME)

	SET @MATRICULA = (SELECT IDENT_CURRENT('ALUNOS') AS [IDENT_CURRENT])

	INSERT INTO MATRICULA (MATRICULA, CURSO, MATERIA, PROFESSOR, PERLETIVO) VALUES (@MATRICULA, @CURSO, @MATERIA, @PROFESSOR, @PERLETIVO)
END;

EXEC sp_CadastraAluno  @NOME= 'Henrique', @CURSO = 'ENG', @MATERIA = 'BDA', @PROFESSOR = 1, @PERLETIVO = 2020

SELECT * FROM MATRICULA 