-- CRIAR BACKUP SELECT * INTO VENDSA_BKP FROM VENDAS

--ddl (comandos de criação de tabelas, comandos que definem o que eu quero fazer)
CREATE TABLE Vendas
(
    ID_VENDA INT IDENTITY CONSTRAINT PK_VENDAS PRIMARY KEY, --sempre dar nome para constraint
    IDADE INT CONSTRAINT CHK_IDADE CHECK ([IDADE]>= 18),
    ID_CLIENTE INT CONSTRAINT FK_CLIENTE FOREIGN KEY
        REFERENCES Clientes (ClienteCodigo)
)

INSERT VENDAS (IDADE, ID_CLIENTE) VALUES (66, 1) -- INSERIR REGISTRO

CREATE TABLE Compras
(
    ID_COMPRA INT IDENTITY CONSTRAINT PK_COMPRA PRIMARY KEY,
    VENDA INT,
    NOME VARCHAR(20)

    CONSTRAINT FK_COMPRA_VENDA FOREIGN KEY (VENDA)
        REFERENCES Vendas(ID_VENDA)

)

INSERT Compras (VENDA, NOME) VALUES (1, 'vamo')

SELECT * FROM VENDAS

SELECT * FROM Compras

UPDATE VENDAS SET IDADE = 30, ID_CLIENTE = 5 WHERE ID_VENDA = 3 --ATUALIZAR

DELETE VENDAS WHERE IDADE = 66 AND ID_CLIENTE = 1 --DELETE

DROP TABLE VENDAS